# Generated by Django 4.2.3 on 2023-07-14 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Номер телефона в формате +79112345678', max_length=12, null=True, unique=True, verbose_name='Номер телефона')),
                ('phone_is_confirmed', models.BooleanField(default=False, verbose_name='Телефон подтвержден')),
                ('convert_already', models.BooleanField(default=False, verbose_name='Была ли хотя бы 1 конвертация ')),
                ('amount_of_converts', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='кол-во конвертаций')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
