# Generated by Django 4.2.3 on 2023-07-13 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('current_status', models.CharField(choices=[('OC', 'Заказ создан'), ('CS', 'Конвертация успешна'), ('CF', 'Конвертация провалена'), ('LI', 'Пользователь зашел под номером телефона'), ('WP', 'Ожидает оплаты'), ('PE', 'Ошибка оплаты'), ('SU', 'Заказ оплачен'), ('FD', 'Файл скачан')], default='OC', max_length=2, verbose_name='Статус')),
                ('phone_is_confirmed', models.BooleanField(default=False, verbose_name='Телефон подтвержден')),
                ('need_to_pay', models.BooleanField(default=False, verbose_name='Нужно ли оплатить конвертацию')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачена ли конвертация')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convert_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ на конвертацию',
                'verbose_name_plural': 'Заказы на конвертацию',
            },
        ),
    ]
