# Generated by Django 4.2.3 on 2023-08-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона пользователя')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('slug', models.CharField(default='0', max_length=100, verbose_name='Слаг для url')),
                ('current_status', models.CharField(choices=[('OC', 'Заказ создан'), ('CS', 'Конвертация успешна'), ('CF', 'Конвертация провалена'), ('LI', 'Пользователь зашел под номером телефона'), ('WP', 'Ожидает оплаты'), ('PE', 'Ошибка оплаты'), ('SU', 'Заказ оплачен'), ('FD', 'Файл скачан')], default='OC', max_length=2, verbose_name='Статус')),
                ('need_to_pay', models.BooleanField(default=False, verbose_name='Нужно ли оплатить')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Заказ на конвертацию',
                'verbose_name_plural': 'Заказы на конвертацию',
            },
        ),
    ]
