# Generated by Django 4.2.3 on 2023-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertorder',
            name='slug',
            field=models.CharField(default='0', max_length=100, verbose_name='Слаг для url'),
        ),
    ]
