# Generated by Django 4.2.3 on 2023-07-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertorder',
            name='phone_is_confirmed',
        ),
    ]
