# Generated by Django 4.2.3 on 2023-07-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_order', '0002_remove_convertorder_phone_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertorder',
            name='need_to_pay',
            field=models.BooleanField(default=False, verbose_name='Нужно ли оплатить'),
        ),
        migrations.AlterField(
            model_name='convertorder',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
