# Generated by Django 4.2.3 on 2023-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_order', '0002_convertorder_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertorder',
            name='user',
        ),
        migrations.AddField(
            model_name='convertorder',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона пользователя'),
        ),
    ]
