# Generated by Django 4.2.3 on 2023-07-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convert_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='%d/%m/%Y/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('0', 'Неизвестный тип'), ('1', 'Исходный №1'), ('2', 'Исходный №2'), ('3', 'Конвертированный')], default='0', max_length=2, verbose_name='Тип файла (1, 2 или 3)')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='convert_order.convertorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
    ]
