# Generated by Django 4.2.3 on 2023-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='%d/%m/%Y/', verbose_name='Файл'),
        ),
    ]
