# Generated by Django 4.2.3 on 2023-07-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
