# Generated by Django 4.2.3 on 2023-07-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert_order', '0001_initial'),
        ('files', '0002_alter_files_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
