# Generated by Django 4.2.3 on 2023-07-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_rename_files_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Загруженный файл', 'verbose_name_plural': 'Загруженные файлы'},
        ),
    ]
